CREATE TABLE test ( id INTEGER NOT NULL PRIMARY KEY );
CREATE TABLE test2 ( id INTEGER NOT NULL PRIMARY KEY );
CREATE TABLE test3 ( id INTEGER NOT NULL PRIMARY KEY );
CREATE TABLE test4 ( id INTEGER NOT NULL PRIMARY KEY );
CREATE TABLE test5 ( id INTEGER NOT NULL PRIMARY KEY );
